workflows:
  android-native-workflow:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Clean Project
        script: |
          # تنظيف ملفات البناء القديمة لحل مشاكل الـ Compiler
          ./gradlew clean
      - name: Build Android
        script: |
          # بناء نسخة الـ Debug
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
