workflows:
  android-native-workflow:
    name: Android Native Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_ndk: 25.2.9519653
      vars:
        JAVA_VERSION: "17"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Make Gradlew Executable
        script: |
          chmod +x gradlew || true
      - name: Build Android APK
        script: |
          if [ -f ./gradlew ]; then
            ./gradlew assembleDebug --no-daemon
          else
            gradle assembleDebug --no-daemon
          endif
    artifacts:
      - app/build/outputs/apk/**/*.apk
